name: adele
favicon: null
layout_spectrum: 0.39309175685048103
typography_spectrum: 0.8919975783210248
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.315546513767913
  lightness: 0.04715369432233274
  saturation: 0.6536877655889839
  rhythmicContrast: 0.8269902695901692
purpose: []
